-- -------------------------------------------------------------
-- Services Data
--
-- Database: postgres
-- Generation Time: 2022-11-14 23:34:36.6720
-- -------------------------------------------------------------

INSERT INTO "Service" ("id", "title", "description", "img_name", "category_id") VALUES
(1, 'Chair Massage', 'Receive a 15 minute traditional Swedish massage that will help alleviate your stress, tension, pain or stiffness while increasing your energy level, alertness and creativity. Our professional Massage Therapists perform the massage in a specially designed ergonomic massage chair while you’re fully clothed, using traditional Swedish massage techniques', 'massage-chair.jpg', 1),
(2, 'Aroma Therapy Oils', 'Natural oils extracted from flowers, bark, stems, leaves, roots or other parts of a plant to enhance psychological and physical well-being. The inhaled aroma from these essential oils is widely believed to stimulate brain function. Essential oils can also be absorbed through the skin, where they travel through the bloodstream and can promote whole-body healing. A form of alternative medicine, aromatherapy is gaining momentum. It is used for a variety of applications, including pain relief, mood enhancement and increased cognitive function. There are a wide number of essential oils available, each with its own healing properties. Oils are the heart of aromatherapy.', 'addons-aroma-oils.jpg', 2),
(3, 'Therapeutic Cupping Massage', 'Pain Management, Injury and Surgical Recovery, Athletic Performance Enhancement, Clears Stagnation, Drains & Moves Fluids, Relieves Inflammation, Nervous System Sedation, Expels Congestion, Stretches Muscles & Connective Tissue, Loosens Adhesions, Nourishing Blood Supply To The Skin, Helps With Weight Loss, Helps Reduce Cellulite.', 'addons-cupping.jpg', 2),
(4, 'Dry Brushing', 'Adding a dry brush to your massage helps by exfoliating & stimulating the lymphatic system and circulation starts at the feet and works it way up including under arms. Proven to help with cellulite, removes dead skin cells, and aids in decreasing bloating. Great with aroma therapy to accelerate blood flow.', 'addons-drybrush.jpg', 2),
(5, 'Massage Flame', 'Experience the Flame an irresistible Hot Oil Massage. 100% Natural Multi-Sensory Experience. Lavish blend of exotic palm kernel oil, soy oil, Shea butter, jojoba oil, Vitamin E, organic coconut oil, and essential oils. It leaves the skin silky smooth and irresistibly scented.', 'addons-flame.jpg', 2),
(6, 'Herbal Infused Heat Packs', 'This treatment covers the entire torso for total body warmth sending you in to a new world of Bliss and Deep Relaxation. Lavender, valerian root, white willow, chamomile, rosemary, peppermint, spearmint, hops, yellow dock, lemongrass, cinnamon, yarrow, premium flax seeds. Ideal for clients that suffer from arthritis, back pain, stress relief and many other common ailments.', 'addons-heatpacks.jpg', 2),
(7, 'Ice Massage', 'A great way to apply ice therapy to a sports injury. It has many benefits over ice bags, and is especially useful for injuries like shin splints, plantar fasciitis, and hip flexor strains. Benefits for a better penetration of the cooling effects of ice therapy when compared to traditional ice bags. It also uses the effects of massage to mobilize the soft tissue. When applied to superficial muscles, it can help to decrease inflammation and to reduce pain.', 'addons-ice.jpg', 2),
(8, 'Lash Extensions', 'Coming Soon', 'addons-lash.jpg', 2),
(9, 'Rain Drop Therapy', 'Kills Bacteria Pathogens, Reduces Inflammation, Supports the Immune System, Eases Respiratory Discomfort, Lifts the Spirit, Relaxes Muscles, Curbs Digestive Upset, Relieves Body & Joint Pain, Balances Energy, Restores Calmness, Increases Concentration', 'addons-raindrop.jpg', 2),
(10, 'CBD Infused Massage', 'CBD oil reduces inflammation, is a potent pain reliever. It alleviates stress and anxiety, may help with skin cancer and other skin stresses. Also helps clear toxins'' ultimate skin protector and moisturizer.', 'addons-cbd.jpg', 2),
(11, 'Paraffin Wax Treatment', 'The benefits of paraffin wax are endless, used in ancient times Romans would pour hot waxes on the body in preparation for a massage. The French embraced paraffin wax therapy by spreading it on their wounds to accelerate healing. Paraffin wax is helpful with Arthritis, Bursitis, Eczema, Fibromyaxlia, Fibrosis, Inflammation, Muscle Spasm, Psoriasis, Scar Tissue, Stiff Joints, and Tendonitis.', 'addons-paraffin.jpg', 2),
(12, 'LightStim Therapy', 'Temporarily relieves arthritic pain, muscle and joint pain, and stiffness. Increases blood circulation, speed healing, and diminishes bruising. Also is a natural solution to help achieve clear and healthy skin by treating existing blemishes, minimizing breakouts, and recapturing your radiant glow. It is the most effective and affordable technology for achieving healthy and youthful skin.', 'addons-lightstim.jpg', 2),
(13, 'Lava Shells', 'When filled with the patented self-heating technology of Lava Gel, Lava Shells heat for up to 45-minutes, depending on the method of application, giving you the same heat as a full hot stone massage with just two shells – no electricity of equipment needed.', 'addons-lava-shell.jpg', 2),
(14, 'Glacier Shells', 'Enhancement to any facial to reduces dark circles & puffiness around the eyes, help to suppress acne flare-ups, help to firm and tighten skin prior to a makeup application, increase circulation, diminish the appearance of wrinkles, suppress hair growth, help to rejuvenate the skin and reduce skin inflammation.', 'addons-glacier-shell.jpg', 2),
(15, 'Breast Enhancement', 'The specially designed vacuum pump can improve size and shape or breast safely and comfortably. The vacuum pulls fat toward the breast tissue, permeating the breast cells, leaving them fuller.', NULL, 3),
(16, 'Butt Lifting', 'Cupping is all the rage for lifting and enhancing the butt. 2 sessions per week for 10 weeks, and the results will be noticeable.', NULL, 3),
(17, 'Fat Eliminator Sculpting', 'Safely and effectively improve the shape of the belly, thighs, butt, and back by using point percussion therapy with the scrub cup to help eliminate fat on the body. Cupping has been used for overall health by the negative pressure and suction causing the nervous system to sedate, treating high blood pressure, relieving pain in the back and neck, loosening stiff muscles, and treating anxiety, fatigue, and even rheumatism.', NULL, 3),
(18, 'Coffee & Cocoa Treatment', 'These natural oils are a purifying dose of detoxification; they also provide illuminating moisture reintroducing the glow to overly dry skin.', 'addons-cocoa.jpg', 2),
(19, 'Couples #1', 'Swedish Massage with Aromatherapy. Performed in a serene setting, the duet massage encourages unity, connection and collective calm. Ease stress and unwind as two therapists perform side-by-side Swedish Massages that help the two of you relax. With a Cooling Mint Eye mask. Including reflexology and a scalp massage. Breathing treatment & Herbal infused hot towel with a foot detox herbal spray.', 'massage-couples-1.jpg', 5),
(20, 'Couples #2', 'Hot Stones & Aromatherapy. Performed in a serene setting, the duet massage encourages unity, connection and collective calm. Ease stress and unwind as two therapists perform side-by-side Swedish Massages that help the two of you relax.With a Cooling Mint Eye mask. Including reflexology and a scalp massage. Breathing treatment, with a Herbal infused detox spray.', 'massage-couples-2.jpg', 5),
(21, 'Couples #3', 'Deep Tissue Massage, Hot Stone, Aromatherapy & Indian Scalp Massage. Performed in a serene setting, the duet massage encourages unity, connection and collective calm. Ease stress and unwind as two therapists perform side-by-side Deep Tissue Massages that help the two of you relax.With a Cooling Eye mask. With our own Herbal breathing treatment and herbal foot detox spray.', 'massage-couples-3.jpg', 5),
(22, 'Pampered Party Packet', '1 Hour and 35 Minutes of Swedish Massage, Hot Stones, Reflexology, Aromatherapy, and a Pressure Point Release Rain Drop Facial and Pearl Mask.', 'massage-deluxe-party.jpg', 5),
(23, 'Silk Spine Massage', 'Gliding around spine very gently pushing tired knotted up muscles away from the spine gently caressing the nerves in the surrounding are to relive and relax your central nervous system. Allowing your central nervous system to flow freely and unblocked. Better sleep and fewer headaches along with lowered anxiety. Overall mood improvement!', 'massage-deluxe-silk-spine.jpg', 5),
(24, 'Cleopatra''s Dead Sea', 'Purifies hydrates and restores elasticity adding moisture to skin for a vibrant complexion. Along with making the skin soft supple and smoother looking. It reaches deep in to the pores, removing grime which slow down the nourishing process. Chamomile, jojoba oil, Maris salt, vitamin B5, Aloe Vera, fruit oil, Vitamin E. With an added Jade Stone Massage to cool down the skin and give it that added natural glow.', 'facials-cleopatra.jpg', 6),
(25, 'Custom Back Facial', 'Purify your neck, shoulders and back, with a custom organic blend made moments before your treatment.', 'facials-back.jpg', 6),
(26, 'Don''t Crease Me Poppy Seed', 'Lemons and poppy seed facial wrinkles and fine line reducer. It exfoliates and polishes leaving skin radiant! With all organic products featuring lemon, poppy seeds ,coconut oil rosemary nutmeg and vitamin E and B-5 almond oil , pecan shells, grape fruit and clove.', 'facials-poppy-seed.jpg', 6),
(27, 'Facial Cupping Face Lift Treatment', 'This gentle, but effective treatment that makes us look and feel youthful and radiant. I use a light suction technique, as an all-natural alternative to a surgical facelift or laser and chemical treatments. It tones your facial muscles and reduces under eye puffiness. The suction created, lifts, tones, and plumps muscles. It relaxes facial muscles and plumps the lines father time has etched on your face. Its deep invigorating action increases elastin and collagen; preserving our youthfulness. It reverses gravity’s effects on your face, like hanging upside would; giving a youthful glow. It gives your face a lymphatic drainage and increases circulation, resulting in a clearer, cleaner, more even complexion with such beautiful color you will forget to wear makeup! It’s completely painless and leaves no marks.', 'facials-cupping.jpg', 6),
(28, 'Fire & Ice', 'Positively stimulating eminence facial. With infusion of fresh apple and grape natural fruit acids for an active organic exfoliation. Paprika and other fresh herbs stimulate circulation and deeply detoxify the skin. With a cold Globe Massage! This facial finishes with cooling application of chilled organic masques suited to your skins needs. Fire & Ice will leave your skin glowing, toned, detoxified and firm.', 'facials-fire-ice.jpg', 6),
(29, 'Goodbye Pore Me', 'Minimize pores and wipes out dead surface from your face. Rare Amazonian white clay, Herbal Moisturizer, cinnamon Bark, Ginger Root, Apricot Kernel Oil, Vitamin E, Avocado Oil Sweet Almond Oil.', 'facials-goodbye-pore-me.jpg', 6),
(30, 'Honey Bee Pollen My Feathers', 'This mask works against Acne and eczema. Perfect for anti-aging absorbs free Radicals.', 'facials-honey-bee.jpg', 6),
(31, 'Just For Him Hot Towel', 'This tailor-made treatment utilizes actives that address his skin. The face is deeply cleansed, moisturized, and soothed to reduce sensitivity commonly associated with daily shaving. An energizing facial mask applied during a scalp massage is a must to leave him feeling revived and relaxed, so that challenges of the day can be boldly met and conquered with confidence.',  'facials-just-for-him.jpg',6),
(32, 'Pumpkin Pie Without A Limit', 'Pumpkin, naturally rich in beta carotene and active enzymes, renews tired skin and clays gently draw out impurities and toxins. It is also a powerful antioxidant that has the ability to make your skin glow. Vitamin A also makes its appearance in pumpkin with the ability to exfoliate and reveal brighter skin and minimize the appearance of sun damage.', 'facials-pumpkin-pie.jpg', 6),
(33, 'Volcanic Detox', 'Its fights free radicals, rejuvenates your face while recharging your cells. It keeps you moisturized all day helping you pull out hard to get white heads. Charcoal, volcanic ash, Acai and goji berry, green tea and fig antioxidants.', 'facials-volcanic-detox.jpg', 6),
(34, 'Phytomer Resurfacing Facial', 'This facial purifies and cleanses the skin of city dwellers by providing a deep cleanse with our Cleansing Foaming Cream that helps tired, polluted dull skin. 1st with our Multi- Resurfacing Exfoliant that reduces the depth of wrinkles and restores radiance. 2nd we apply the Pure Pore Heating Mask that completely depollutes, sanitizes, and leaves pores unclogged. Lastly we moisturize with City Life Face &amp; Eye Contour Sorbet Cream that protects skin from pollutants in the air.', 'facials-phytomer.jpg', 6),
(35, 'Luminating Phytomer Facial', 'This facial firms, brightens, and tightens along with protecting the skin from pollutants in the air. Next we exfoliate with our Marine Scrub that’s for normal, combination or oily skin. It helps loosen impurities and eliminates dead cells that make skin appear dull and restore the shine and softness. Then we top it off with the Luminous Complexion and Eye Radiance Plasticizing Masks. To seal in masks we apply Oligoforce Contouring Serum. Then finish off with City Life Face &amp; Eye Contour Sorbet Cream that protects skin from pollutants in the air.', 'facials-luminating-phytomer.jpg', 6),
(36, 'Confidence Facial', 'This facial helps reduce acne blemishing and scaring by providing a deep cleanse with our Gentle Cleansing Milk for all skin types. 1st we exfoliate with our Marine Scrub that’s for normal, combination or oily skin. It helps loosen impurities and eliminates dead cells that make skin appear dull and restores the shine and softness. 2nd we apply the Pure Pore Heating Mask that completely depollutes, sanitizes, and leave pores unclogged. Then to seal everything in we apply the Dark Spot Complexion Gel Serum that reduces the unevenness of the skin. Then to set that we apply the Purifying Enforcement Serum with Oligomer. Lastly we finish off with City Life Face &amp; Eye Contour Sorbet Cream that protects skin from pollutants in the air.', 'facials-confidence.jpg', 6),
(37, 'Vagacial Facial', 'Using our Phytomer products that help replenish minerals that you lose from stress or other contraindications. This facial helps with discoloration of the skin, ingrown hair, and stretch marks.', 'facials-vagacial.jpg', 6),
(38, 'Fanny Facial', 'Using our Phytomer products that help replenish minerals that you lose from stress or other contraindications. This facial helps with discoloration of the skin, ingrown hair, and stretch marks.', 'facials-fanny.jpg', 6),
(39, 'Microdermabrasion Facial', 'A non-invasive procedure that uses tiny crystals or other exfoliating surfaces to help remove the superficial layer of dead skin cells.', 'facials-microderm-addon.jpg', 6),
(40, 'Black Detox Add-on', 'Self-Heating Back Detox that pulls toxins out, relieves tension, water retention, and relaxes deeply.', 'facials-black-detox-addon.jpg', 6),
(41, 'Vacuum and Spray Unit', 'The Vacuum and Spray Unit both cleanses the skin and helps removes impurities', NULL, 7),
(42, 'High Frequency Unit', 'A high frequency machine used to send electrical currents and strong vibrations through a person’s skin to help in healing and relieving pain. It is used as one of the final steps of a facial extraction. It can be warming and soothing or stimulating and can deliver a mild antiseptic effect. It benefits the skin in many ways such as increasing metabolism, producing heat inside the body tissues, stimulating glandular activity, increasing the circulation of blood, aids in the elimination and absorption, penetrates more deeply into the skin, and creates a germicidal action while it is being used in the direct method mode helping kill bacteria on the skin.', NULL, 7),
(43, 'Galvanic Unit', 'A versatile tool thats primarily used to introduce water-soluble materials into the skin and disincrustation. Skincare professionals have used it for 50 years to refresh and energize the skin. It also provides a gentle massage that helps focus cellular energy and enhance circulation.', NULL, 7),
(44, 'Health Coaching', 'Advice and programs designed to improve your health and overall well-being', NULL, 8),
(45, 'Color Light Therapy', NULL, NULL, 9),
(46, 'Yoga Sessions', NULL, NULL, 10),
(47, 'Champagne & Rose Massage', 'Absorb the rich, romantic, renewing bouquet of the Champagne and Rose Collection. The massage oil delivers smooth, long-lasting glide and is rich in nutrients. Perfect for couples, Valentine''s Day or Mother''s Day services. Paraben-Free.', 'massage-champagne.jpg', 1),
(48, 'Cold Stone Massage', 'Cold stone attributes that minimizes soreness, pulls excess heat from the body, stregthen the body on a cellular level, easily remove heat from the body. It also provides a deep state of relaxation, reduction of swelling or inflammation due to scar tissue, trauma or injuries to muscles. Cold stone helps alleviate anxiety, depression, PMS, sinusitis, high blood pressure, and fatigue.', 'massage-cold-stone.jpg', 1),
(49, 'Deep Tissue', 'A style of massage that is designed to get into the connective tissue of the body, rather than just the surface muscles. Many clients have a more intense experience with a deep tissue massage, but also feel that it is more beneficial, because it addresses deep-seated muscle pains. Like other types of massage,deep tissue is most beneficial when undertaken on a regular basis, so that therapist and client can work together to correct long term problems, relax the body, and prevent injury.', 'massage-deep-tissue.jpg', 1),
(50, 'Himalayan Salt Stone', 'An innovative, detoxifying, healing technique using warm salt stones to ground and balance the body’s electromagnetic field, entral nervous system and meridians.', 'massage-himalayan.jpg', 1),
(51, 'Hot Stone', 'Hot stone helps by improve overall mental, spiritual,and physical wellness. Native Americans used hot stones to detoxify and to find harmony and balance. Basalt stones, polished, hardened lava rocks, are heated by hot water. The heated stones are then placed strategically along pressure points to help melt away tension creating a calming atmosphere. Stress, deadlines, anxiety, and other life annoyances disappear long enough for your mind to relax at the deepest level. Over all it creates a sense of well being.', 'massage-hot-stone.jpg', 1),
(52, 'Medical Massage', 'Medical massage involves therapeutic assessment, manipulation, and movement of the locomotor soft tissues to reduce or eliminate pain or dysfunction. A unique multidisciplinary approach is utilized to restore structural balance throughout the body, which allows focus on prevention and rehabilitation of musculoskeletal dysfunctions, chronic pain and sports injuries. Primary modalities include functional assessment, myofascial release, neuromuscular therapy,scar tissue mobilization techniques, neuromuscular re-education, PNF stretching, strengthening, and specific client home-care protocols.', 'massage-medical.jpg', 1),
(53, 'Myofascial Release Blade Massage', 'The focus of myofascial release is on the myofascial, the web of interconnected connective tissue that wraps around and surrounds every muscle, bone, nerve, blood vessel and organ in the body. Trauma, inflammatory responses, and/or surgical procedures create Myofascial restrictions that can produce tensile pressures of approximately 2,000 pounds per square inch on pain sensitive structures that do not show up in many of the standard tests x-rays, myelograms, CAT scans, electromyography, etc.)', 'massage-myofascial.jpg', 1),
(54, 'Indian Scalp Massage', 'The Indian scalp massage improves blood flow to the head and neck, which increases the distribution of nutrients and encourages healing throughout the body, beneficial for relieving stress and tension, improving concentration, increasing joint mobility and flexibility in the neck and shoulders, improving blood circulation and lymphatic flow, reducing fatigue, relieving insomnia, headaches, migraines and sinusitis. Enjoy a deeply calming and relaxing treatment that will also leave you feeling energized and revitalized!', 'massage-indian-scalp.jpg', 1),
(55, 'Lymphatic Drainage Massage', 'Manual Lymphatic Drainage is a form of massage that stimulates the lymphatic system with gentle massaging strokes. The light rhythmical massage encourages the lymphatic system to eliminate metabolic waste products, excess fluid and bacteria, promotes detoxification, facilitates healing and supports the immune system. Studies have shown that it helps stop and reduce the production of cellulite after a series of treatments along with a healthy diet and exercise.
', 'massage-lymph.jpg', 1),
(56, 'Pregnancy Massage', '(Please consult with your doctor during your first trimester to get approval for massage.) Enhance your special time with massage therapy. Massage can help alleviate tension, fluid retention, fatigue and stress and improve circulation in the feet, legs, lower back, hips and neck. You will be lying comfortably on your side for a relaxing Swedish massage. Before making an appointment, please check with your physician to make sure that massage is right for you.', 'massage-pregnancy.jpg', 1),
(57, 'Reflexology', 'A holistic therapy that aims to restore and maintain the body’s natural balance and encourage healing. According to Chinese medicine, the sensory nerves of the internal organs throughout the body are mainly gathered around the soles of the feet. Through application of pressure on these reflexes without the use of tools, reflexology is proven to produce potent therapeutic benefits for a wide range of health conditions. It can also produce one of the most sublime relaxation experiences while it rejuvenates and revitalizes all aspects of our body and being.', 'massage-reflexology.jpg', 1),
(58, 'Sports Massage', 'Originally designed for athletes, to help prepare their bodies for optimal performance, recover after a big event, or function well during training. However it is useful for anyone with chronic pain, injury or range-of-motion issues. Sports Massage Emphasizes Prevention and Healing of injuries to the Muscles and Tendons.', 'massage-sports.jpg', 1),
(59, 'Swedish Massage', 'This classic massage treatment is also known as a Relaxation Massage and the goal is to relax the entire body through various techniques such as long, flowing strokes using light to medium pressure. Your session will address such issues as stress, tension and mild to moderate muscle discomfort. Swedish massage is often recommended for first time massage clients and is excellent for improving circulation and flexibility while easing tension.', 'massage-swedish.jpg', 1),
(60, 'Trigger Point', 'A bodywork technique that involves the applying of pressure to tender muscle tissue in order to relieve pain and dysfunction in other parts of the body. The purpose of trigger point therapy is to eliminate pain and to re-educate the muscles into pain-free habits. After several treatments, the swelling and stiffness of neuromuscular pain is reduced; range of motion is increased; tension is relieved; and circulation, flexibility and coordination are improved.', 'massage-trigger-point.jpg', 1),
(61, 'Wine Therapy', 'Generally red wine when used in skin care products fights free radicals, stimulates blood circulation, rejuvenates, increases skin elasticity, eases the nerves, firms, whitens, and leaves your skin bright and glowing These stimulating properties also softens wrinkles and fine lines and is altogether very useful in battling the effects of aging skin. It is thought that the ingredients in the wine massage numbs nerve endings and so allows muscles to reach a greater state of relaxation. This relaxation then allows a vasodilation of the blood vessels that surround muscle tissue and means more healing nutrients can get to the damaged tissue.', 'massage-wine.jpg', 1),
(62, 'Barefoot Massage: Deepest Deep Tissue Massage Possible', 'Reduces Chronic Pain. This Deep Tissue massage works further into the fascia. It also will release trigger points and connective tissues. It is a slow and more forceful in the application. Not only adds more pressure but it also adds compression. And it throws myofascial stretching into the mix. Compression massage squeezes the entire body from above and below. It also affects internal organs. It is a soft structural integration that realigns the body. Skeletal adjustments often occur during a session. It also has myofascial benefits that relax and stretch contracted muscles. This unique modality combines three therapies into one. It also Improves Flexibility, No Residual Soreness, Reduces Stress, Effects Last Longer.', 'massage-barefoot.jpg', 1),
(63, '4 Handed Massage', 'A therapeutic, duet massage is performed by two therapists whose coordinated movements induce relaxation and ease tension. To promote self balance and clarity. A soothing scalp massage and reflexology will leave you with a sense of calm and well-being. The organic,balancing massage oil used during treatment soothes the senses and nourishes the skin. Emerge renewed, refreshed and relaxed.', 'massage-deluxe-4-handed.jpg', 1),
(64, 'Oxygey Session', 'A high purity way to get oxygen for recreation and relaxation. Indulge in Aroma O2 oxygen giving you a mild safe euphoric feeling. Oxygen is nutrient for the brain, The brain of an adult accounts for 2 to 3 percent of the whole body in terms of weight but consumes 20% of oxygen absorbed into the body. Brain cells need 200 liters of oxygen a day for proper operation.', NULL, 11),
(65, 'Foot Soak', 'Is the ionic foot bath machine right for me? With the increase in the number of chemicals and hazardous materials introduced in the last few decades, there has been a dramatic increase in incidences of auto-immune disease, allergies and common infections. Although people are living longer, we face new types of diseases and infections as we become immune to older ones. There are tens of thousands of chemicals in use today and more than a forth of these are known to be toxic and nothing is known about their interactive effects. Body fat has been tested that contains residue of hundreds of chemicals. Metals, such as mercury and cadmium are everywhere and impossible to avoid. Lead can block red blood cell formation. Chemicals can act as toxins that can block receptor sites on cells, and cause changes in calcium homeostasis selectively killing cells, and alter expression of gene products. Metals and chemical toxins weaken the immune system and cause increased vulnerability to virus, bacterial fungal and parasitic infections. In an attempt to detoxify these substances, our bowels, kidneys and liver are being overloaded. Our eliminative channels have become blocked or dysfunctional, because, in conjunction with these synthetic chemicals, and the western diet that is so acid forming and de-vitalized. ', NULL, 12),
(66, 'Honey Relax', 'A relaxation ritual richly crafted blend of sugar crystals, nutrient-rich antioxidants and essential oils creating a comprehensive exfoliation treatment. Spearmint leaf, organic , Lime, Lavender and Sandalwood are included in the 50 Minute Scrub.', 'scrubs-weightloss-honey.jpg', 13),
(67, 'Polish Me Perfect', 'Raw Sugar Cane granules produce glycolic acid, help refine pores, boost collagen and elastin, bind moisture and brighten skin all over along with reducing the sight of cellulite helping you become fully balanced using Grape Seed Oil,Coffee, Fresh Coconut , Geranium, Rosemary and Lavender.', 'scrubs-weightloss-polish.jpg', 13),
(68, 'Weight Loss Body Wraps', 'After the mixture is brushed on the body you are then wrapped in plastic wrap and thermal blanket. Clay body wraps absorb and draw out toxins in skin, bentonite clay particles hold a negative electrical charge, while toxins have a positive charge. The negatively charged particles draw the toxins out of skin through the pores. The theory goes back centuries, and it has been proven that Cleopatra used clay poultices as skin treatments.', 'scrubs-weightloss-wrap.jpg', 13),
(69, 'Arm Waxing', NULL, 'waxing-arms.jpg', 14),
(70, 'Back Waxing', NULL, 'waxing-back.jpg', 14),
(71, 'Bikini Waxing', NULL, 'waxing-bikini.jpg', 14),
(72, 'Brazilian Bikini Waxing', 'waxing-brazilian.jpg', NULL, 14),
(73, 'Face Waxing', NULL, 'waxing-face.jpg', 14),
(74, 'Full Leg Waxing', NULL, 'waxing-full-leg.jpg', 14),
(75, 'Chest Waxing', NULL, 'waxing-chest.jpg', 14),
(76, 'Chin Waxing', NULL, 'waxing-chin.jpg', 14),
(77, 'Extended Bikini Waxing', NULL, 'waxing-extended-bikini.jpg', 14),
(78, 'Eyebrow Waxing', NULL, 'waxing-eyebrow.jpg', 14),
(79, 'Lip Waxing', NULL, 'waxing-lip.jpg', 14),
(80, 'Lower Leg Waxing', NULL, 'waxing-lower-leg.jpg', 14),
(81, 'Underarm Waxing', NULL, 'waxing-underarm.jpg', 14),
(82, 'Upper Leg Waxing', NULL, 'waxing-upper-leg.jpg', 14),
(83, 'Eyebrow Tint', NULL, 'eyes-brow-tint.jpg', 15),
(84, 'Eyelash Tint', NULL, 'eyes-lash-tint.jpg', 15),
(85, 'Refill', NULL, 'eyes-refill.jpg', 15),
(86, 'Eyelash Perm', NULL, 'eyes-lash-perm.jpg', 15),
(87, 'Eyelash Extensions', NULL, 'eyes-lash-ext.jpg', 15),
(88, 'Eyelash Extensions with Volume', NULL, 'eyes-lash-ext-volume.jpg', 15),
(89, 'Blow Dry', NULL, 'finishing-touches-blowdry.jpg', 16),
(90, 'Up-do''s', 'Braiding, up-styles and curls', 'finishing-touches-up-do.jpg', 16),
(91, 'Ironworks', NULL, 'straightening-organic-thermal-straightening-haircut.jpg', 16),
(92, 'French Braid', NULL, 'finishing-touches-french-braid.jpg', 16),
(93, 'Dutch Braid', NULL, 'finishing-touches-dutch-braid.jpg', 16),
(94, 'Haircut & Blow Dry', NULL, 'haircut-blow-dry.jpg', 17),
(95, 'Kid''s Haircut (12 & under)', NULL, 'haircut-kids.jpg', 17),
(96, 'Dry Cut', NULL, 'haircut-dry-cut.jpg',  17),
(97, 'Bangs', NULL, 'haircut-bangs.jpg', 17),
(98, 'Glossing', 'Performed following chemical service to add intense shine', 'haircolor-gloss.jpg', 18),
(99, 'Temporary Color Rinse', NULL, 'haircolor-rinse.jpg', 18),
(100, 'Color Correction', NULL, 'haircolor-color-correction.jpg', 18),
(101, 'All Over Color', NULL, 'haircolor-allover.jpg', 18),
(102, 'All Over Color with Shampoo & Condition (Travel Size)', NULL, 'haircolor-allover-shampoo.jpg', 18),
(103, 'All Over Bleach', NULL, 'haircolor-allover-bleach.jpg', 18),
(104, 'Bleach Root Touch-Up', NULL, 'haircolor-bleach-root.jpg', 18),
(105, 'Root Touch-Up', NULL, 'haircolor-root-touchup.jpg', 18),
(106, 'Chemical Services', NULL, 'haircolor-chemical.jpg', 18),
(107, 'Hair Extensions Install', 'Prices vary, contact us for a consultation ', 'hair-ext.jpg', 30),
(108, 'Foil', 'The ultimate in hair coloring, providing smoothness, protection and brilliant shine for long-lasting color', 'highlight-foil.jpg', 19),
(109, 'Foil with Haircut', NULL, 'highlight-foil-haircut.jpg', 19),
(110, 'Partial Foil', 'Up to 12 foils', 'highlight-partial-foil.jpg', 19),
(111, 'Partial Foil with Haircut', NULL, 'highlight-partial-foil-haircut.jpg', 19),
(112, 'Accent Foil', 'Up to 4 foils', 'highlight-accent-foil.jpg', 19),
(113, 'Dimensional Color', 'Two or more colors to create a unique, multi-dimensional look', 'highlight-dimensional.jpg', 19),
(114, 'Ombre Hair', 'Coloring technique where a gradual fading of color from dark to light, or vice-versa, is achieved. Additional cost for add-on color', 'highlight-ombre.jpg', 19),
(115, 'Ombre with Haircut', NULL, 'highlight-ombre-haircut.jpg', 19),
(116, 'Balayage Freehand', 'Technique of applying highlights, or lowlights, with select pieces of hair receiving the color enhancement', 'highlight-balayage.jpg', 19),
(117, 'Balayage with Haircut', NULL, 'highlight-balayage-haircut.jpg', 19),
(118, 'Highlights', NULL, 'highlight-hightlights.jpg', 19),
(119, 'Partial Highlights', NULL, 'highlight-partial-hightlights.jpg', 19),
(120, 'Keep It Curl Organic Color Systems Treatment', NULL, 'hair-treatments-keep-it-curl.jpg', 20),
(121, 'Aqua Boost Organic Treatment', NULL, 'hair-treatments-aqua-boost.jpg', 20),
(122, 'Power Build Treatment', NULL, 'hair-treatments-breakage.jpg', 20),
(123, 'Organic Color Systems Smooth+ Treatment', NULL, 'hair-treatments-organic-colour.jpg', 20),
(124, 'Dry Scalp & Dandruff', 'Organic Custom Blend & Scalp Tonic', 'hair-treatments-organic-scalp.jpg', 20),
(125, 'Dry Scalp', 'Dry Scalp Tonic', 'hair-treatments-scalp.jpg', 20),
(126, 'Organic Color Systems Intensive Clarifying', NULL, 'hair-treatments-clarifying.jpg', 20),
(127, 'Organic Color Systems Brazilian Blowout Treatment', NULL, 'hair-treatments-brazilian-blowout.jpg', 20),
(128, 'Peace Of Mind Scalp Treatment', NULL, 'hair-treatments-pom-scalp.jpg', 20),
(129, 'Rainbow Chakra Treatment', NULL, 'hair-treatments-rainbow-chakra.jpg', 20),
(130, 'Charcoal Treatment', NULL, 'hair-treatments-charcoal.jpg', 20),
(131, 'Organic Lice Removal Treatment', 'Must book 2 weeks in advance', 'hair-treatments-lice.jpg', 20),
(132, 'Silk Press', NULL, 'hair-treatments-silk.jpg', 20),
(133, 'Loc Maintenance', NULL, 'locs-maintainence.jpg', 21),
(134, 'Loc Styling', NULL, 'locs-styling.jpg', 21),
(135, 'Hot Towel Mani', 'Wrapping hands in herbal & aromatherapy infused towels to insure full relaxation and deep moisturization. We clean up the cuticle, file, and finish with a vegan friendly all organic non-toxic, free of DBP, formaldehyde, formaldehyde resin, and non GMO nail lacquer.', 'manicures-hot-towel.jpg', 22),
(136, 'Mani Bowl', 'Using clean water, fresh herbs and aromatherapy oils. We clean up the cuticle, file, and finish with a vegan friendly all organic non-toxic, free of DBP, formaldehyde, formaldehyde resin, and non GMO nail lacquer.', 'manicures-bowl.jpg', 22),
(137, 'CBD Oil Add On', NULL, 'manicures-cbd-oil.jpg', 22),
(138, 'Hot Towel Pedi', 'Unlike most nail salons where you dip your feet in the same contaminated foot bath bowl, we use fresh clean hot towels that are infused with herbs & aromatherapy oils, ensuring you never get a foot fungus. Using hot stones to massage tired aching feet, an all-natural organic foot and leg scrub made in house and a revitalizing foot massage. We clean up the cuticle, file, and finish with a vegan friendly organic non-toxic, free of DBP, formaldehyde, formaldehyde resin, and non GMO nail lacquer.', 'pedicures-hot-towel.jpg', 22),
(139, 'Pedi Powl', 'Unlike most nail salons where you dip your feet in the same contaminated foot bath, we use fresh clean water with fresh herbs and aromatherapy oils, ensuring you never get a foot fungus. Using tea tree, coconut milk, and lavender to help soften the feet. We clean up the cuticle, file, and finish with a vegan friendly all organic non-toxic, free of DBP, formaldehyde, formaldehyde resin, and non GMO nail lacquer.', 'oxygen-foot-soak-benefits.jpg', 22),
(140, 'Everyday', NULL, 'makeup-everyday.jpg', 23),
(141, 'Bridal', NULL, 'makeup-bridal.jpg', 23),
(142, 'Haircut', NULL, 'mens-haircut.jpg', 24),
(143, 'Gray Blending', NULL, 'mens-gray.jpg',  24),
(144, 'Signature Experience', 'Includes scalp massage, hot towel, hair cut, and facial hair trim', 'mens-signature.jpg',  24),
(145, 'Beard Trimmings', NULL, 'mens-beardtrims.jpg',  24),
(146, 'Shampoo & Diffuse', NULL, 'natural-shampoo.jpg',  25),
(147, 'Basic Corn Row', NULL, 'natural-basic-corn-row.jpg', 25),
(148, 'Corn Row with Design', NULL, 'natural-corn-row-design.jpg', 25),
(149, 'Bantu Knots', NULL, 'natural-bantu.jpg', 25),
(150, 'Basic Wave', NULL, 'perm-basic.jpg', 26),
(151, 'Basic Wave with Haircut', NULL, 'perm-basic-haircut.jpg', 26),
(152, 'Specialty Wave', NULL, 'perm-specialty.jpg', 26),
(153, 'Specialty with Haircut', NULL, 'perm-specialty-haircut.jpg', 26),
(154, 'Press & Curl', NULL, 'sets-press-curl.jpg', 27),
(155, 'Shampoo Services with Two-Stand Twist', NULL, 'sets-shampoo-rinse.jpg', 27),
(156, 'Shampoo Services with Flat-Twist Set', NULL, 'sets-shampoo-rinse-flat.jpg', 27),
(157, 'Single Twist Comb Twist', NULL, 'sets-single-twist.jpg', 27),
(158, 'Double Twist Two Strand', NULL, 'sets-double-twist.jpg', 27),
(159, 'Straw Set', NULL, 'sets-straw.jpg', 27),
(160, 'Rod Set', NULL, 'sets-rod.jpg', 27),
(161, 'Kinky Twist', NULL, 'specialty-kinky.jpg', 28),
(162, 'Rope Twist', NULL, 'specialty-rope.jpg', 28),
(163, 'Micro Braids', NULL, 'specialty-micro.jpg', 28),
(164, 'Organic Colors Systems Ultimate Blowout', NULL, 'straightening-organic-blowout.jpg', 29),
(165, 'Organic Colors Systems Blowout with Haircut', NULL, 'straightening-organic-blowout-haircut.jpg', 29),
(166, 'Organic Colors Systems Thermal Straightening', NULL, 'straightening-organic-thermal-straightening.jpg', 29),
(167, 'Organic Colors Systems Thermal Straightening with Haircut', NULL, 'straightening-organic-thermal-straightening-haircut.jpg', 29),
(168, 'Retouch', NULL, 'straightening-retouch.jpg', 29),
(169, 'Retouch with Haircut', NULL, 'straightening-retouch-haircut.jpg', 29),
(170, 'Venus Legacy', 'Venus Legacy is an advanced non-invasive medical device that effectively resolves challenging Face and body aesthetic needs, such as nonsurgical circumferential reduction, cellulite reduction, skin tightening, and wrinkle reduction. It decreases swelling and helps tighten the skin. We also advise all our patients receiving laser treatments that they too should improve the tightening of their skin. (We will have packets available when you purchase 6 youll get the 7th one free.)', NULL, 3),
(171, 'Apricot Cream Rogue', NULL, 'apricot-cream-rouge.jpg', 31),
(172, 'Bisque Souffle Foundation', NULL, 'bisque-souffle-foundation.jpg',  31),
(173, 'Brightening Violet Powder', NULL, 'brightening-violet-powder.jpg', 31),
(174, 'Crimson Cream Rogue', NULL, 'crimson-cream-rouge.jpg', 31),
(175, 'Dark Cashmere Powder Compact', NULL, 'dark-cashmere-powder-compact.jpg', 31),
(176, 'Honey Souffle Foundation', NULL, 'honey-souffle-foundation.jpg', 31),
(177, 'Light Cashmere Powder Compact', NULL, 'light-cashmere-powder-compact.jpg', 31),
(178, 'Medium Beige Souffle Foundation', NULL, 'medium-beige-souffle-foundation.jpg', 31),
(179, 'Medium Cashmere Powder Compact', NULL, 'medium-cashmere-powder-compact.jpg', 31),
(180, 'Porcelain Cashmere Powder Compact', NULL, 'porcelain-cashmere-powder-compact.jpg', 31),
(181, 'Cashmere Powder Dark Refill', NULL, 'refill-dark.jpg', 31),
(182, 'Cashmere Powder Light Refill', NULL, 'refill-light.jpg', 31),
(183, 'Cashmere Powder Medium Refill', NULL, 'refill-medium.jpg', 31),
(184, 'Cashmere Powder Porcelain Refill', NULL, 'refill-porcelain.jpg', 31),
(185, 'Cashmere Powder Violet Refill', NULL, 'refill-violet.jpg', 31),
(186, 'True Beige Souffle Foundation', NULL, 'true-beige-souffle-foundation.jpg', 31),
(187, 'Violet Brightening Powder Compact', NULL, 'violet-brightening-powder-compacts.jpg', 31),
(188, 'Yellow Cameo Souffle Foundation', NULL, 'yellow-cameo-souffle-foundation.jpg', 31),
(189, 'Black Mascara', NULL, 'black-mascara.jpg', 32),
(190, 'Brown Cake Mascara', NULL, 'mascara.jpg', 32),
(191, 'Black Cake Mascara', NULL, 'mascara.jpg', 32),
(192, 'Besame Red', NULL, '1920-besamered-lipstick.jpg', 33),
(193, 'Noir Red', NULL, '1930-noirred-lipstick.jpg', 33),
(194, 'Tango Red', NULL, '1930-tangored-lipstick.jpg', 33),
(195, 'Carmine', NULL, '1931-carmine-lipstick.jpg', 33),
(196, 'Merlot', NULL, '1933-merlot-lipstick.jpg', 33),
(197, 'Cherry Red', NULL, '1935-cherryred-lipstick.jpg', 33),
(198, 'American Beauty', NULL, '1945-americanbeauty-lipstick.jpg', 33),
(199, 'Red Velvet', NULL, '1946-redvelvet-lipstick.jpg', 33),
(200, 'Exotic Pink', NULL, '1955-exoticpink-lipstick.jpg', 33),
(201, 'Red Hot Red', NULL, '1959-redhotred-lipstick.jpg', 33),
(202, 'Portrait Pink', NULL, '1963-portraitpink-lipstick.jpg', 33),
(203, 'Debutante Pink', NULL, '1967-debutantepink-lipstick.jpg', 33),
(204, 'Dusty Rose', NULL, '1969-dustyrose-lipstick.jpg', 33),
(205, 'Chocolate Kiss', NULL, '1970-chocolatekiss-lipstick.jpg', 33);